/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package healthos_lib

/** The base Uri for API calls */
const BASEURI string = "http://{%[1]v}/api/v1"

var Config struct {
    /** Replace the value of Host with an appropriate value */
    Host string
    /** The OAuth 2.0 access token to be set before API calls */
    /** Replace the value of OAuthAccessToken with an appropriate value */
    OAuthAccessToken string
}
