/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package food_pkg


/*
 * Interface for the FOOD_IMPL
 */
type FOOD interface {
    SearchFoodRestaurants (string) (interface{}, error)

    GetAllFoodBrands (int64, int64) (interface{}, error)

    GetFoodItemsByRestaurant (int64, int64, string) (interface{}, error)

    SearchFoodBrands (string) (interface{}, error)

    GetFoodItem (string) (interface{}, error)

    GetAllFoodItems (int64, int64) (interface{}, error)

    SearchFoodItems (string) (interface{}, error)

    GetAllFoodRestaurants (int64, int64) (interface{}, error)

    GetFoodItemsByBrand (int64, int64, string) (interface{}, error)
}

/*
 * Factory for the FOOD interaface returning FOOD_IMPL
 */
func NewFOOD() FOOD {
    return &FOOD_IMPL{}
}