/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package models_pkg


/*
 * Structure for the custom type RequestAccessTokenRequest
 */
type RequestAccessTokenRequest struct {
    GrantType       string          `json:"grant_type" form:"grant_type"` //TODO: Write general description for this field
    ClientId        string          `json:"client_id" form:"client_id"` //TODO: Write general description for this field
    ClientSecret    string          `json:"client_secret" form:"client_secret"` //TODO: Write general description for this field
    Scope           string          `json:"scope" form:"scope"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MedicinesResponse
 */
type MedicinesResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Form            string          `json:"form" form:"form"` //TODO: Write general description for this field
    StandardUnits   int64           `json:"standardUnits" form:"standardUnits"` //TODO: Write general description for this field
    PackageForm     string          `json:"packageForm" form:"packageForm"` //TODO: Write general description for this field
    Price           float64         `json:"price" form:"price"` //TODO: Write general description for this field
    Size            string          `json:"size" form:"size"` //TODO: Write general description for this field
    Manufacturer    string          `json:"manufacturer" form:"manufacturer"` //TODO: Write general description for this field
    Constituents    []*Constituent  `json:"constituents" form:"constituents"` //TODO: Write general description for this field
    Schedule        Schedule        `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    MedicineId      string          `json:"medicine_id" form:"medicine_id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Constituent
 */
type Constituent struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Strength        string          `json:"strength" form:"strength"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Schedule
 */
type Schedule struct {
    Category        string          `json:"category" form:"category"` //TODO: Write general description for this field
    Label           string          `json:"label" form:"label"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GenericsResponse
 */
type GenericsResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    GenericId       string          `json:"generic_id" form:"generic_id"` //TODO: Write general description for this field
    TheraupticUses  []string        `json:"therauptic_uses" form:"therauptic_uses"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type FoodItemsResponse
 */
type FoodItemsResponse struct {
    Calories        int64           `json:"calories" form:"calories"` //TODO: Write general description for this field
    ItemName        string          `json:"item_name" form:"item_name"` //TODO: Write general description for this field
    ServingQty      float64         `json:"serving_qty" form:"serving_qty"` //TODO: Write general description for this field
    ServingUnit     string          `json:"serving_unit" form:"serving_unit"` //TODO: Write general description for this field
    FoodBrandId     string          `json:"food_brand_id" form:"food_brand_id"` //TODO: Write general description for this field
    FoodItemId      string          `json:"food_item_id" form:"food_item_id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LabTestsResponse
 */
type LabTestsResponse struct {
    AlternateName   string          `json:"alternate_name" form:"alternate_name"` //TODO: Write general description for this field
    LabTestData     LabTestData     `json:"lab_test_data" form:"lab_test_data"` //TODO: Write general description for this field
    LabTestId       string          `json:"lab_test_id" form:"lab_test_id"` //TODO: Write general description for this field
    LabTestName     string          `json:"lab_test_name" form:"lab_test_name"` //TODO: Write general description for this field
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LabTestData
 */
type LabTestData struct {
    OrderingInformation  string          `json:"Ordering information" form:"Ordering information"` //TODO: Write general description for this field
    AlternateNames       string          `json:"Alternate names" form:"Alternate names"` //TODO: Write general description for this field
    Laboratory           string          `json:"Laboratory" form:"Laboratory"` //TODO: Write general description for this field
    TestCode             string          `json:"Test Code" form:"Test Code"` //TODO: Write general description for this field
    SpecimenTypes        string          `json:"Specimen types" form:"Specimen types"` //TODO: Write general description for this field
    ContainerTypes       string          `json:"Container types" form:"Container types"` //TODO: Write general description for this field
    MinimumAdultVolume   string          `json:"Minimum Adult Volume" form:"Minimum Adult Volume"` //TODO: Write general description for this field
    Frequency            string          `json:"Frequency" form:"Frequency"` //TODO: Write general description for this field
    ExternalLaboratory   string          `json:"External Laboratory" form:"External Laboratory"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type DiseasesResponse
 */
type DiseasesResponse struct {
    DiseaseName     string          `json:"disease_name" form:"disease_name"` //TODO: Write general description for this field
    DiseaseCat      string          `json:"disease_cat" form:"disease_cat"` //TODO: Write general description for this field
    DiseaseInfo     string          `json:"disease_info" form:"disease_info"` //TODO: Write general description for this field
    DiseaseId       string          `json:"disease_id" form:"disease_id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type ExercisesResponse
 */
type ExercisesResponse struct {
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    Category             string          `json:"category" form:"category"` //TODO: Write general description for this field
    CaloryCount          string          `json:"calory_count" form:"calory_count"` //TODO: Write general description for this field
    CardioSubcategory    string          `json:"cardio_subcategory" form:"cardio_subcategory"` //TODO: Write general description for this field
    PrimaryMuscleGroup   string          `json:"primary_muscle_group" form:"primary_muscle_group"` //TODO: Write general description for this field
    ExerciseId           string          `json:"exercise_id" form:"exercise_id"` //TODO: Write general description for this field
    SearchScore          float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchDiseasesResponse
 */
type SearchDiseasesResponse struct {
    DiseaseName     string          `json:"disease_name" form:"disease_name"` //TODO: Write general description for this field
    DiseaseCat      string          `json:"disease_cat" form:"disease_cat"` //TODO: Write general description for this field
    DiseaseInfo     string          `json:"disease_info" form:"disease_info"` //TODO: Write general description for this field
    DiseaseId       string          `json:"disease_id" form:"disease_id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllDiseasesResponse
 */
type AllDiseasesResponse struct {
    DiseaseName     string          `json:"disease_name" form:"disease_name"` //TODO: Write general description for this field
    DiseaseCat      string          `json:"disease_cat" form:"disease_cat"` //TODO: Write general description for this field
    DiseaseInfo     string          `json:"disease_info" form:"disease_info"` //TODO: Write general description for this field
    DiseaseId       string          `json:"disease_id" form:"disease_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MedicineInteractionsResponse
 */
type MedicineInteractionsResponse struct {
    Generic         string          `json:"generic" form:"generic"` //TODO: Write general description for this field
    Interactions    []*Interaction  `json:"interactions" form:"interactions"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Interaction
 */
type Interaction struct {
    Items           []*Item         `json:"items" form:"items"` //TODO: Write general description for this field
    Severity        string          `json:"severity" form:"severity"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    Source          string          `json:"source" form:"source"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Item
 */
type Item struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchExercisesResponse
 */
type SearchExercisesResponse struct {
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    Category             string          `json:"category" form:"category"` //TODO: Write general description for this field
    CaloryCount          string          `json:"calory_count" form:"calory_count"` //TODO: Write general description for this field
    CardioSubcategory    string          `json:"cardio_subcategory" form:"cardio_subcategory"` //TODO: Write general description for this field
    PrimaryMuscleGroup   string          `json:"primary_muscle_group" form:"primary_muscle_group"` //TODO: Write general description for this field
    ExcerciseId          string          `json:"excercise_id" form:"excercise_id"` //TODO: Write general description for this field
    SearchScore          float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchExercisesResponse16
 */
type SearchExercisesResponse16 struct {
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    Category             string          `json:"category" form:"category"` //TODO: Write general description for this field
    CaloryCount          string          `json:"calory_count" form:"calory_count"` //TODO: Write general description for this field
    CardioSubcategory    string          `json:"cardio_subcategory" form:"cardio_subcategory"` //TODO: Write general description for this field
    PrimaryMuscleGroup   string          `json:"primary_muscle_group" form:"primary_muscle_group"` //TODO: Write general description for this field
    ExerciseId           string          `json:"exercise_id" form:"exercise_id"` //TODO: Write general description for this field
    SearchScore          float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllExercisesResponse
 */
type AllExercisesResponse struct {
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    CaloryCount          string          `json:"calory_count" form:"calory_count"` //TODO: Write general description for this field
    Category             string          `json:"category" form:"category"` //TODO: Write general description for this field
    CardioSubcategory    string          `json:"cardio_subcategory" form:"cardio_subcategory"` //TODO: Write general description for this field
    PrimaryMuscleGroup   string          `json:"primary_muscle_group" form:"primary_muscle_group"` //TODO: Write general description for this field
    ExcerciseId          string          `json:"excercise_id" form:"excercise_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllExercisesResponse18
 */
type AllExercisesResponse18 struct {
    Name                 string          `json:"name" form:"name"` //TODO: Write general description for this field
    CaloryCount          string          `json:"calory_count" form:"calory_count"` //TODO: Write general description for this field
    Category             string          `json:"category" form:"category"` //TODO: Write general description for this field
    CardioSubcategory    string          `json:"cardio_subcategory" form:"cardio_subcategory"` //TODO: Write general description for this field
    PrimaryMuscleGroup   string          `json:"primary_muscle_group" form:"primary_muscle_group"` //TODO: Write general description for this field
    ExerciseId           string          `json:"exercise_id" form:"exercise_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchFoodItemsResponse
 */
type SearchFoodItemsResponse struct {
    Calories        int64           `json:"calories" form:"calories"` //TODO: Write general description for this field
    ItemName        string          `json:"item_name" form:"item_name"` //TODO: Write general description for this field
    ServingQty      float64         `json:"serving_qty" form:"serving_qty"` //TODO: Write general description for this field
    ServingUnit     string          `json:"serving_unit" form:"serving_unit"` //TODO: Write general description for this field
    FoodBrandId     string          `json:"food_brand_id" form:"food_brand_id"` //TODO: Write general description for this field
    FoodItemId      string          `json:"food_item_id" form:"food_item_id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllFoodItemsResponse
 */
type AllFoodItemsResponse struct {
    ItemName        string          `json:"item_name" form:"item_name"` //TODO: Write general description for this field
    Calories        int64           `json:"calories" form:"calories"` //TODO: Write general description for this field
    ServingQty      float64         `json:"serving_qty" form:"serving_qty"` //TODO: Write general description for this field
    ServingUnit     string          `json:"serving_unit" form:"serving_unit"` //TODO: Write general description for this field
    FoodItemId      string          `json:"food_item_id" form:"food_item_id"` //TODO: Write general description for this field
    FoodBrandId     string          `json:"food_brand_id" form:"food_brand_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchFoodBrandsResponse
 */
type SearchFoodBrandsResponse struct {
    Logo            string          `json:"logo" form:"logo"` //TODO: Write general description for this field
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    FoodBrandId     string          `json:"food_brand_id" form:"food_brand_id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllFoodBrandsResponse
 */
type AllFoodBrandsResponse struct {
    BrandName       string          `json:"brand_name" form:"brand_name"` //TODO: Write general description for this field
    FoodBrandId     string          `json:"food_brand_id" form:"food_brand_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type FoodItemsByBrandResponse
 */
type FoodItemsByBrandResponse struct {
    ItemName        string          `json:"item_name" form:"item_name"` //TODO: Write general description for this field
    Calories        int64           `json:"calories" form:"calories"` //TODO: Write general description for this field
    ServingQty      float64         `json:"serving_qty" form:"serving_qty"` //TODO: Write general description for this field
    ServingUnit     string          `json:"serving_unit" form:"serving_unit"` //TODO: Write general description for this field
    FoodItemId      string          `json:"food_item_id" form:"food_item_id"` //TODO: Write general description for this field
    FoodBrandId     string          `json:"food_brand_id" form:"food_brand_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchFoodRestaurantsResponse
 */
type SearchFoodRestaurantsResponse struct {
    Logo               string          `json:"logo" form:"logo"` //TODO: Write general description for this field
    Name               string          `json:"name" form:"name"` //TODO: Write general description for this field
    FoodRestaurantId   string          `json:"food_restaurant_id" form:"food_restaurant_id"` //TODO: Write general description for this field
    SearchScore        float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllFoodRestaurantsResponse
 */
type AllFoodRestaurantsResponse struct {
    RestaurantName     string          `json:"restaurant_name" form:"restaurant_name"` //TODO: Write general description for this field
    FoodRestaurantId   string          `json:"food_restaurant_id" form:"food_restaurant_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type FoodItemsByRestaurantResponse
 */
type FoodItemsByRestaurantResponse struct {
    ItemName        string          `json:"item_name" form:"item_name"` //TODO: Write general description for this field
    Calories        int64           `json:"calories" form:"calories"` //TODO: Write general description for this field
    ServingQty      float64         `json:"serving_qty" form:"serving_qty"` //TODO: Write general description for this field
    ServingUnit     string          `json:"serving_unit" form:"serving_unit"` //TODO: Write general description for this field
    FoodItemId      string          `json:"food_item_id" form:"food_item_id"` //TODO: Write general description for this field
    FoodBrandId     string          `json:"food_brand_id" form:"food_brand_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllGenericsResponse
 */
type AllGenericsResponse struct {
    Name                            string          `json:"name" form:"name"` //TODO: Write general description for this field
    PregnancyCategory               string          `json:"pregnancy_category" form:"pregnancy_category"` //TODO: Write general description for this field
    LactationCategory               string          `json:"lactation_category" form:"lactation_category"` //TODO: Write general description for this field
    Instructions                    string          `json:"instructions" form:"instructions"` //TODO: Write general description for this field
    Faqs                            string          `json:"faqs" form:"faqs"` //TODO: Write general description for this field
    GenricId                        int64           `json:"genric_id" form:"genric_id"` //TODO: Write general description for this field
    SideEffects                     string          `json:"side_effects" form:"side_effects"` //TODO: Write general description for this field
    HowItWorks                      string          `json:"how_it_works" form:"how_it_works"` //TODO: Write general description for this field
    TherapeuticClass                string          `json:"therapeutic_class" form:"therapeutic_class"` //TODO: Write general description for this field
    UsedFor                         string          `json:"used_for" form:"used_for"` //TODO: Write general description for this field
    Strength                        string          `json:"strength" form:"strength"` //TODO: Write general description for this field
    Schedule                        string          `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    AlcoholInteractionDescription   string          `json:"alcohol_interaction_description" form:"alcohol_interaction_description"` //TODO: Write general description for this field
    AlcoholNteraction               bool            `json:"alcohol_nteraction" form:"alcohol_nteraction"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MedicinesByGenericResponse
 */
type MedicinesByGenericResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Form            string          `json:"form" form:"form"` //TODO: Write general description for this field
    StandardUnits   int64           `json:"standardUnits" form:"standardUnits"` //TODO: Write general description for this field
    PackageForm     string          `json:"packageForm" form:"packageForm"` //TODO: Write general description for this field
    Price           float64         `json:"price" form:"price"` //TODO: Write general description for this field
    Size            string          `json:"size" form:"size"` //TODO: Write general description for this field
    Manufacturer    string          `json:"manufacturer" form:"manufacturer"` //TODO: Write general description for this field
    Constituents    []*Constituent  `json:"constituents" form:"constituents"` //TODO: Write general description for this field
    Schedule        Schedule        `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    MedicineId      string          `json:"medicine_id" form:"medicine_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchLabTestsResponse
 */
type SearchLabTestsResponse struct {
    AlternateName   string          `json:"alternate_name" form:"alternate_name"` //TODO: Write general description for this field
    LabTestData     LabTestData     `json:"lab_test_data" form:"lab_test_data"` //TODO: Write general description for this field
    LabTestId       string          `json:"lab_test_id" form:"lab_test_id"` //TODO: Write general description for this field
    LabTestName     string          `json:"lab_test_name" form:"lab_test_name"` //TODO: Write general description for this field
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllLabTestsResponse
 */
type AllLabTestsResponse struct {
    LabTestName     string          `json:"lab_test_name" form:"lab_test_name"` //TODO: Write general description for this field
    AlternateName   string          `json:"alternate_name" form:"alternate_name"` //TODO: Write general description for this field
    LabTestId       string          `json:"lab_test_id" form:"lab_test_id"` //TODO: Write general description for this field
    LabTestData     LabTestData34   `json:"lab_test_data" form:"lab_test_data"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LabTestData34
 */
type LabTestData34 struct {
    OrderingInformation     string          `json:"Ordering information" form:"Ordering information"` //TODO: Write general description for this field
    Laboratory              string          `json:"Laboratory" form:"Laboratory"` //TODO: Write general description for this field
    TestCode                string          `json:"Test Code" form:"Test Code"` //TODO: Write general description for this field
    SpecimenTypes           string          `json:"Specimen types" form:"Specimen types"` //TODO: Write general description for this field
    ContainerTypes          string          `json:"Container types" form:"Container types"` //TODO: Write general description for this field
    CollectionInstructions  string          `json:"Collection Instructions" form:"Collection Instructions"` //TODO: Write general description for this field
    Frequency               string          `json:"Frequency" form:"Frequency"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchMedicinesResponse
 */
type SearchMedicinesResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Form            string          `json:"form" form:"form"` //TODO: Write general description for this field
    StandardUnits   int64           `json:"standardUnits" form:"standardUnits"` //TODO: Write general description for this field
    PackageForm     string          `json:"packageForm" form:"packageForm"` //TODO: Write general description for this field
    Price           float64         `json:"price" form:"price"` //TODO: Write general description for this field
    Size            string          `json:"size" form:"size"` //TODO: Write general description for this field
    Manufacturer    string          `json:"manufacturer" form:"manufacturer"` //TODO: Write general description for this field
    Constituents    []*Constituent  `json:"constituents" form:"constituents"` //TODO: Write general description for this field
    Schedule        Schedule        `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    Id              string          `json:"id" form:"id"` //TODO: Write general description for this field
    MedicineId      string          `json:"medicine_id" form:"medicine_id"` //TODO: Write general description for this field
    SearchScore     float64         `json:"search_score" form:"search_score"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllMedicinesResponse
 */
type AllMedicinesResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Form            string          `json:"form" form:"form"` //TODO: Write general description for this field
    StandardUnits   int64           `json:"standardUnits" form:"standardUnits"` //TODO: Write general description for this field
    PackageForm     string          `json:"packageForm" form:"packageForm"` //TODO: Write general description for this field
    Price           float64         `json:"price" form:"price"` //TODO: Write general description for this field
    Size            string          `json:"size" form:"size"` //TODO: Write general description for this field
    Manufacturer    string          `json:"manufacturer" form:"manufacturer"` //TODO: Write general description for this field
    Constituents    []*Constituent  `json:"constituents" form:"constituents"` //TODO: Write general description for this field
    Schedule        Schedule        `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    MedicineId      string          `json:"medicine_id" form:"medicine_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AlternativeMedicinesResponse
 */
type AlternativeMedicinesResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Form            string          `json:"form" form:"form"` //TODO: Write general description for this field
    StandardUnits   int64           `json:"standardUnits" form:"standardUnits"` //TODO: Write general description for this field
    PackageForm     string          `json:"packageForm" form:"packageForm"` //TODO: Write general description for this field
    Price           float64         `json:"price" form:"price"` //TODO: Write general description for this field
    Size            string          `json:"size" form:"size"` //TODO: Write general description for this field
    Manufacturer    string          `json:"manufacturer" form:"manufacturer"` //TODO: Write general description for this field
    Constituents    []*Constituent  `json:"constituents" form:"constituents"` //TODO: Write general description for this field
    Schedule        Schedule        `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    MedicineId      string          `json:"medicine_id" form:"medicine_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SimilarMedicinesResponse
 */
type SimilarMedicinesResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Form            string          `json:"form" form:"form"` //TODO: Write general description for this field
    StandardUnits   int64           `json:"standardUnits" form:"standardUnits"` //TODO: Write general description for this field
    PackageForm     string          `json:"packageForm" form:"packageForm"` //TODO: Write general description for this field
    Price           float64         `json:"price" form:"price"` //TODO: Write general description for this field
    Size            string          `json:"size" form:"size"` //TODO: Write general description for this field
    Manufacturer    string          `json:"manufacturer" form:"manufacturer"` //TODO: Write general description for this field
    Constituents    []*Constituent  `json:"constituents" form:"constituents"` //TODO: Write general description for this field
    Schedule        Schedule        `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    MedicineId      string          `json:"medicine_id" form:"medicine_id"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type PopularUsageResponse
 */
type PopularUsageResponse struct {
    Generic         string          `json:"generic" form:"generic"` //TODO: Write general description for this field
    Usages          []*Usage        `json:"usages" form:"usages"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Usage
 */
type Usage struct {
    Term            string          `json:"term" form:"term"` //TODO: Write general description for this field
    Count           int64           `json:"count" form:"count"` //TODO: Write general description for this field
    Percent         float64         `json:"percent" form:"percent"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CommonSideEffectsResponse
 */
type CommonSideEffectsResponse struct {
    Generic         string          `json:"generic" form:"generic"` //TODO: Write general description for this field
    SideEffects     []*SideEffect   `json:"side_effects" form:"side_effects"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SideEffect
 */
type SideEffect struct {
    Term            string          `json:"term" form:"term"` //TODO: Write general description for this field
    Count           int64           `json:"count" form:"count"` //TODO: Write general description for this field
    Percent         float64         `json:"percent" form:"percent"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SearchManufacturersResponse
 */
type SearchManufacturersResponse struct {
    ManufacturerId  int64           `json:"manufacturer_id" form:"manufacturer_id"` //TODO: Write general description for this field
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type AllManufacturersResponse
 */
type AllManufacturersResponse struct {
    ManufacturerId  int64           `json:"manufacturer_id" form:"manufacturer_id"` //TODO: Write general description for this field
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MedicinesByManufacturerResponse
 */
type MedicinesByManufacturerResponse struct {
    Name            string          `json:"name" form:"name"` //TODO: Write general description for this field
    Form            string          `json:"form" form:"form"` //TODO: Write general description for this field
    StandardUnits   int64           `json:"standardUnits" form:"standardUnits"` //TODO: Write general description for this field
    PackageForm     string          `json:"packageForm" form:"packageForm"` //TODO: Write general description for this field
    Price           float64         `json:"price" form:"price"` //TODO: Write general description for this field
    Size            string          `json:"size" form:"size"` //TODO: Write general description for this field
    Manufacturer    string          `json:"manufacturer" form:"manufacturer"` //TODO: Write general description for this field
    Constituents    []*Constituent  `json:"constituents" form:"constituents"` //TODO: Write general description for this field
    Schedule        Schedule        `json:"schedule" form:"schedule"` //TODO: Write general description for this field
    MedicineId      string          `json:"medicine_id" form:"medicine_id"` //TODO: Write general description for this field
}
