/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package autocomplete_pkg


/*
 * Interface for the AUTOCOMPLETE_IMPL
 */
type AUTOCOMPLETE interface {
    GetExercises (string) (interface{}, error)

    GetDiseases (string) (interface{}, error)

    GetLabTests (string) (interface{}, error)

    GetFoodItems (string) (interface{}, error)

    GetGenerics (string) (interface{}, error)

    GetMedicines (string) (interface{}, error)
}

/*
 * Factory for the AUTOCOMPLETE interaface returning AUTOCOMPLETE_IMPL
 */
func NewAUTOCOMPLETE() AUTOCOMPLETE {
    return &AUTOCOMPLETE_IMPL{}
}