/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package chat_pkg


/*
 * Interface for the CHAT_IMPL
 */
type CHAT interface {
    GetExcercisesChat () (interface{}, error)

    GetFoodItemsChat () (interface{}, error)

    GetMedicineChat () (interface{}, error)
}

/*
 * Factory for the CHAT interaface returning CHAT_IMPL
 */
func NewCHAT() CHAT {
    return &CHAT_IMPL{}
}