/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package exercises_pkg


/*
 * Interface for the EXERCISES_IMPL
 */
type EXERCISES interface {
    GetExercise (string) (interface{}, error)

    GetAllExercises (int64, int64) (interface{}, error)

    SearchExercises (string) (interface{}, error)
}

/*
 * Factory for the EXERCISES interaface returning EXERCISES_IMPL
 */
func NewEXERCISES() EXERCISES {
    return &EXERCISES_IMPL{}
}