/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package labtests_pkg


/*
 * Interface for the LABTESTS_IMPL
 */
type LABTESTS interface {
    GetLabTest (string) (interface{}, error)

    GetAllLabTests (int64, int64) (interface{}, error)

    SearchLabTests (string) (interface{}, error)
}

/*
 * Factory for the LABTESTS interaface returning LABTESTS_IMPL
 */
func NewLABTESTS() LABTESTS {
    return &LABTESTS_IMPL{}
}