/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package authentication_pkg

import "healthos_lib/models_pkg"

/*
 * Interface for the AUTHENTICATION_IMPL
 */
type AUTHENTICATION interface {
    CreateRequestAccessToken (*models_pkg.RequestAccessTokenRequest) (interface{}, error)
}

/*
 * Factory for the AUTHENTICATION interaface returning AUTHENTICATION_IMPL
 */
func NewAUTHENTICATION() AUTHENTICATION {
    return &AUTHENTICATION_IMPL{}
}