/*
 * healthos_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package druginteractions_pkg


/*
 * Interface for the DRUGINTERACTIONS_IMPL
 */
type DRUGINTERACTIONS interface {
    GetGenericsInteractions (string) (interface{}, error)

    GetMedicineInteractions (string) (interface{}, error)
}

/*
 * Factory for the DRUGINTERACTIONS interaface returning DRUGINTERACTIONS_IMPL
 */
func NewDRUGINTERACTIONS() DRUGINTERACTIONS {
    return &DRUGINTERACTIONS_IMPL{}
}